# SPDX-FileCopyrightText: 2024 Dom Rodriguez <shymega@shymega.org.uk>
#
# SPDX-License-Identifier: GPL-3.0-only


name: Push artifacts to Cachix.
on:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'verma-project' }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            extra-platforms = aarch64-linux armv6l-linux armv7l-linux i686-linux riscv64-linux
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: cachix/cachix-action@v15
        with:
          name: kiosk-nix
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build and push  to Cachix.
        run: nix build github:srid/devour-flake -L --no-link --print-out-paths --override-input flake path:"$GITHUB_WORKSPACE" --impure
